spring.application.name=base-webapp-sb01

spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME_01}
spring.datasource.username=${DB_USER_01}
spring.datasource.password=${DB_PASS_01}
spring.datasource.hikari.schema=${DB_USER_01}


